#cloud-config
write_files:
  - path: /etc/sysctl.conf
    permissions: "0644"
    owner: root
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.all.proxy_arp = 1
runcmd:
  - sysctl -p
  # Accept all ICMP (troubleshooting)
  - iptables -A INPUT -p icmp -j ACCEPT
  # Accept SSH local traffic to the eth0 interface (health checking)
  - iptables -A INPUT -p tcp --dport 22 -d $(hostname -I | awk '{print $1}') -j ACCEPT
  # Drop everything else
  - iptables -A INPUT -j DROP
  # Accept all return transit traffic for established flows
  - iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  # Accept all transit traffic from internal ranges
  # Replace by actual multiple source/destination/proto/ports rules for fine-grained ACLs.
  - iptables -A FORWARD -s 0.0.0.0/0 -d 0.0.0.0/0 -j ACCEPT
  # Drop everything else
  - iptables -A FORWARD -j DROP