#cloud-config
write_files:
  - path: /etc/sysctl.conf
    permissions: "0644"
    owner: root
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.send_redirects = 0

  - path: /tmp/network.conf
    permissions: "0644"
    owner: root
    content: |
      # port configuration
      http_port 3128 ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/opt/websafety/etc/myca.pem
      http_port 3126 intercept
      https_port 3127 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB cert=/opt/websafety/etc/myca.pem

  - path: /tmp/ca.pem
    permissions: "0644"
    owner: root
    content: |
      ${indent(6, certificate_authority_key)}${indent(6, certificate_authority_cert)}

runcmd:
  # Install squid
  - add-apt-repository universe
  - apt update && apt -y upgrade
  - apt install -y iptables
  - curl -L https://raw.githubusercontent.com/diladele/websafety/8.4/core.ubuntu20/02_squid.sh | bash
  - curl -L https://raw.githubusercontent.com/diladele/websafety/8.4/core.ubuntu20/04_websafety.sh | bash
  - curl -L https://raw.githubusercontent.com/diladele/websafety/8.4/core.ubuntu20/squid.conf -o squid.conf
  - curl -L https://raw.githubusercontent.com/diladele/websafety/8.4/core.ubuntu20/05_integrate.sh | bash
  # Configure Trusted Root SSL Certificate for Squid
  - mv /tmp/ca.pem /opt/websafety/etc/ca.pem
  - mv /tmp/network.conf /opt/websafety/etc/squid/network.conf
  - openssl x509 -in /opt/websafety/etc/ca.pem -outform DER -out /opt/websafety/etc/ca.der
  - rm -R -f /var/spool/squid_ssldb
  - /usr/lib/squid/security_file_certgen -c -s /var/spool/squid_ssldb -M 4MB
  - chown -R proxy:proxy /var/spool/squid_ssldb
  - systemctl restart squid
  # Update sysctl config
  - sysctl -p
  # Route inbound traffic into squid
%{ for port in safe_ports ~}
  - iptables -t nat -I PREROUTING 1 -s ${join(",", trusted_cidr_ranges)} -p tcp --dport ${port} -j REDIRECT --to-port 3126
%{ endfor ~}
%{ for port in ssl_ports ~}
  - iptables -t nat -I PREROUTING 1 -s ${join(",", trusted_cidr_ranges)} -p tcp --dport ${port} -j REDIRECT --to-port 3127
%{ endfor ~}
  - systemctl restart squid