name: tfsec-pr-commenter
on:
  push:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.1.0-beta.1
        with:
          github_token: ${{ github.token }}